version: "1.0.0"

# gzingress
server:
  ports:
    - 8080
    - 9090
  cleanup: 1h

logger:
  level: "warn"
  trace: false

rules:
  - host: backend-a.example.com
    backend:
      service_name: backend-a
      service_port: 80
  - host: backend-b.example.com
    backend:
      service_name: backend-b
      service_port: 8080

# gzfly
relay: wss://example.com/ws

auth: client_id:client_secret

actions:
  action1:
    target: client_name:pk
    bind: tcp:0.0.0.0:17890:192.168.1.2:17890
  action2:
    target: client_name:pk
    socks5: 0.0.0.0:17890
